#!/usr/bin/env bash
pip install jupyter-cadquery
jupyter serverextension enable --sys-prefix jupyter_cadquery
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install jupyter-cadquery --no-build
jupyter lab build
